import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar structure for the Physical AI & Humanoid Robotics Textbook
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['index', 'setup', 'quick-start'],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1/index',
        {
          type: 'category',
          label: 'Week 3: ROS 2 Architecture',
          items: ['module-1/week-3/ros2-architecture'],
        },
        {
          type: 'category',
          label: 'Week 4: ROS 2 Nodes, Topics, Services',
          items: ['module-1/week-4/nodes-topics-services'],
        },
        {
          type: 'category',
          label: 'Week 5: Python Integration with rclpy',
          items: ['module-1/week-5/python-rclpy'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2/index',
        {
          type: 'category',
          label: 'Week 6-7: Physics Simulation',
          items: ['module-2/week-6/gazebo-simulation', 'module-2/week-7/unity-rendering'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3/index',
        {
          type: 'category',
          label: 'Week 8-10: Isaac Systems',
          items: ['module-3/week-8/isaac-sim', 'module-3/week-9/vslam-navigation', 'module-3/week-10/nav2-bipedal'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4/index',
        {
          type: 'category',
          label: 'Week 11-13: VLA Systems',
          items: ['module-4/week-11/voice-commands', 'module-4/week-12/llm-planning', 'module-4/week-13/capstone-project'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: ['glossary', 'resources', 'troubleshooting', 'hardware-requirements', 'weekly-breakdown'],
    },
    {
      type: 'category',
      label: 'Assessment Guidelines',
      items: [
        'assessment/module1-guidelines',
        'assessment/module2-guidelines',
        'assessment/module3-guidelines',
        'assessment/module4-guidelines',
      ],
    },
  ],
};

export default sidebars;
